-- Enable PostGIS for location features (optional but recommended for bus apps)
-- create extension if not exists postgis;

-- 1. Create a table for USERS (extends Supabase auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  phone text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- 2. BUS ROUTES (Tuyến xe)
create table public.bus_routes (
  id bigint generated by default as identity primary key,
  route_code text not null, -- e.g. "01", "02"
  name text not null, -- e.g. "BX Gia Lam - BX Yen Nghia"
  operation_time text, -- e.g. "05:00 - 21:00"
  ticket_price decimal(10,2),
  frequency text, -- e.g. "10-15 phut/chuyen"
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. BUS STOPS (Điểm dừng)
create table public.bus_stops (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  lat double precision, -- or use PostGIS: geography(Point, 4326)
  lng double precision,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. ROUTE STOPS (Lộ trình - Các điểm dừng của từng tuyến)
create table public.route_stops (
  id bigint generated by default as identity primary key,
  route_id bigint references public.bus_routes(id) on delete cascade,
  stop_id bigint references public.bus_stops(id) on delete cascade,
  stop_order int not null, -- 1, 2, 3... sequence
  direction int default 0, -- 0: way (lượt đi), 1: return (lượt về)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. SAVED TRIPS / HISTORY (Lịch sử đi lại)
create table public.trip_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  start_stop_id bigint references public.bus_stops(id),
  end_stop_id bigint references public.bus_stops(id),
  start_time timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- SAMPLE DATA (Dữ liệu mẫu)
insert into public.bus_routes (route_code, name, operation_time, ticket_price, frequency)
values 
('01', 'BX Gia Lâm - BX Yên Nghĩa', '05:00 - 21:00', 7000, '10-15 phút'),
('02', 'Bác Cổ - BX Yên Nghĩa', '05:05 - 21:05', 7000, '10-15 phút');

insert into public.bus_stops (name, lat, lng)
values 
('BX Gia Lâm', 21.0478, 105.8778),
('Long Biên', 21.0396, 105.8504),
('Bưu điện Bờ Hồ', 21.0255, 105.8552);

-- Function to handle new user signup (Trigger)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
